import type { AlgoKey } from "./algorithms";

export type Language = "cpp" | "python" | "java";

export const LANGUAGES: Array<{ key: Language; label: string; ext: string }> = [
  { key: "cpp", label: "C++", ext: "cpp" },
  { key: "python", label: "Python", ext: "py" },
  { key: "java", label: "Java", ext: "java" },
];

type Snippet = Record<Language, string[]>;

export const CODE: Record<AlgoKey, Snippet> = {
  access: {
    cpp: ["int access(vector<int>& a, int i) {", "  // O(1) address arithmetic", "  return a[i];", "}"],
    python: ["def access(a, i):", "    # O(1) address arithmetic", "    return a[i]", ""],
    java: ["int access(int[] a, int i) {", "  // O(1) address arithmetic", "  return a[i];", "}"],
  },
  update: {
    cpp: ["void update(vector<int>& a, int i, int v) {", "  // locate slot i", "  a[i] = v;", "}"],
    python: ["def update(a, i, v):", "    # locate slot i", "    a[i] = v", ""],
    java: ["void update(int[] a, int i, int v) {", "  // locate slot i", "  a[i] = v;", "}"],
  },
  insert: {
    cpp: [
      "void insert(vector<int>& a, int i, int v) {",
      "  a.push_back(0);",
      "  for (int k = a.size() - 2; k >= i; k--)",
      "    a[k + 1] = a[k];",
      "",
      "  a[i] = v;",
      "}",
    ],
    python: [
      "def insert(a, i, v):",
      "    a.append(0)",
      "    for k in range(len(a) - 2, i - 1, -1):",
      "        a[k + 1] = a[k]",
      "",
      "    a[i] = v",
      "",
    ],
    java: [
      "void insert(int[] a, int n, int i, int v) {",
      "  // shift right to open a slot",
      "  for (int k = n - 1; k >= i; k--)",
      "    a[k + 1] = a[k];",
      "",
      "  a[i] = v;",
      "}",
    ],
  },
  delete: {
    cpp: [
      "void remove(vector<int>& a, int i) {",
      "  // close the gap at index i",
      "  for (int k = i; k < a.size() - 1; k++)",
      "    a[k] = a[k + 1];",
      "",
      "  a.pop_back();",
      "}",
    ],
    python: [
      "def remove(a, i):",
      "    # close the gap at index i",
      "    for k in range(i, len(a) - 1):",
      "        a[k] = a[k + 1]",
      "",
      "    a.pop()",
      "",
    ],
    java: [
      "void remove(int[] a, int n, int i) {",
      "  // close the gap at index i",
      "  for (int k = i; k < n - 1; k++)",
      "    a[k] = a[k + 1];",
      "",
      "  n--;",
      "}",
    ],
  },
  traverse: {
    cpp: ["void traverse(vector<int>& a) {", "  for (int i = 0; i < a.size(); i++)", "    visit(a[i]);", "}"],
    python: ["def traverse(a):", "    for i in range(len(a)):", "        visit(a[i])", ""],
    java: ["void traverse(int[] a) {", "  for (int i = 0; i < a.length; i++)", "    visit(a[i]);", "}"],
  },
  linear: {
    cpp: [
      "int linearSearch(vector<int>& a, int target) {",
      "  for (int i = 0; i < a.size(); i++) {",
      "    if (a[i] == target) return i;",
      "  }",
      "  return -1;",
      "}",
    ],
    python: [
      "def linear_search(a, target):",
      "    for i in range(len(a)):",
      "        if a[i] == target:",
      "            return i",
      "    return -1",
      "",
    ],
    java: [
      "int linearSearch(int[] a, int target) {",
      "  for (int i = 0; i < a.length; i++) {",
      "    if (a[i] == target) return i;",
      "  }",
      "  return -1;",
      "}",
    ],
  },
  binary: {
    cpp: [
      "int binarySearch(vector<int>& a, int target) {",
      "  int low = 0, high = a.size() - 1;",
      "  while (low <= high) {",
      "    int mid = low + (high - low) / 2;",
      "    if (a[mid] == target) return mid;",
      "    else if (a[mid] < target) low = mid + 1;",
      "    else high = mid - 1;",
      "  }",
      "  return -1;",
      "}",
    ],
    python: [
      "def binary_search(a, target):",
      "    low, high = 0, len(a) - 1",
      "    while low <= high:",
      "        mid = (low + high) // 2",
      "        if a[mid] == target: return mid",
      "        elif a[mid] < target: low = mid + 1",
      "        else: high = mid - 1",
      "",
      "    return -1",
      "",
    ],
    java: [
      "int binarySearch(int[] a, int target) {",
      "  int low = 0, high = a.length - 1;",
      "  while (low <= high) {",
      "    int mid = low + (high - low) / 2;",
      "    if (a[mid] == target) return mid;",
      "    else if (a[mid] < target) low = mid + 1;",
      "    else high = mid - 1;",
      "  }",
      "  return -1;",
      "}",
    ],
  },
  bubble: {
    cpp: [
      "for (int i = 0; i < n - 1; i++) {",
      "  for (int j = 0; j < n - i - 1; j++) {",
      "    if (a[j] > a[j + 1]) {",
      "      swap(a[j], a[j + 1]);",
      "    }",
      "  }",
      "}",
    ],
    python: [
      "for i in range(n - 1):",
      "    for j in range(n - i - 1):",
      "        if a[j] > a[j + 1]:",
      "            a[j], a[j + 1] = a[j + 1], a[j]",
      "",
      "",
      "",
    ],
    java: [
      "for (int i = 0; i < n - 1; i++) {",
      "  for (int j = 0; j < n - i - 1; j++) {",
      "    if (a[j] > a[j + 1]) {",
      "      int t = a[j]; a[j] = a[j + 1]; a[j + 1] = t;",
      "    }",
      "  }",
      "}",
    ],
  },
  selection: {
    cpp: [
      "for (int i = 0; i < n - 1; i++) {",
      "  int minIdx = i;",
      "  for (int j = i + 1; j < n; j++) {",
      "    if (a[j] < a[minIdx]) minIdx = j;",
      "  }",
      "  if (minIdx != i) swap(a[i], a[minIdx]);",
      "}",
    ],
    python: [
      "for i in range(n - 1):",
      "    min_idx = i",
      "    for j in range(i + 1, n):",
      "        if a[j] < a[min_idx]: min_idx = j",
      "",
      "    a[i], a[min_idx] = a[min_idx], a[i]",
      "",
    ],
    java: [
      "for (int i = 0; i < n - 1; i++) {",
      "  int minIdx = i;",
      "  for (int j = i + 1; j < n; j++) {",
      "    if (a[j] < a[minIdx]) minIdx = j;",
      "  }",
      "  if (minIdx != i) { int t = a[i]; a[i] = a[minIdx]; a[minIdx] = t; }",
      "}",
    ],
  },
  insertion: {
    cpp: [
      "for (int i = 1; i < n; i++) {",
      "  int key = a[i];",
      "  int j = i - 1;",
      "  while (j >= 0 && a[j] > key) {",
      "    a[j + 1] = a[j];",
      "    j--;",
      "  }",
      "  a[j + 1] = key;",
      "}",
    ],
    python: [
      "for i in range(1, n):",
      "    key = a[i]",
      "    j = i - 1",
      "    while j >= 0 and a[j] > key:",
      "        a[j + 1] = a[j]",
      "        j -= 1",
      "",
      "    a[j + 1] = key",
      "",
    ],
    java: [
      "for (int i = 1; i < n; i++) {",
      "  int key = a[i];",
      "  int j = i - 1;",
      "  while (j >= 0 && a[j] > key) {",
      "    a[j + 1] = a[j];",
      "    j--;",
      "  }",
      "  a[j + 1] = key;",
      "}",
    ],
  },
};
